DATASET:
  TRAIN_PATH: "./dataset/train"
  TEST_PATH: "./dataset/test"

SAM:
  CHECKPOINT: "/home/peter/Documents/Code/samseg/src/sam_vit_b_01ec64.pth"
  RANK: 512
TRAIN:
  BATCH_SIZE: 1
  NUM_EPOCHS: 5